### ISSUE TITLE
Error on Execution of "Start Recognition"

### ISSUE THREAD

**Issue by djtech2k** [Azure-Samples/Cognitive-Speech-STT-Windows#48] opened 2018-01-12 03:24 UTC
I have built and retrieved a LUIS endpoint.  I have a Speech Services Key and it is stored in the app.  The app builds, but as soon as I click "Start Recognition", I get repetitive error handling:

--- Error received by OnConversationErrorHandler() ---
Error code: LoginFailed
Error text: Transport error

What am I missing?

**Comment by zhouwangzw** [comment] 2018-01-12 06:33
It looks like an authentication error. Have you tried your key with [REST API](https://docs.microsoft.com/en-us/azure/cognitive-services/speech/getstarted/getstartedrest?tabs=Powershell) for verification? More informaiton about authentication can be found [here](https://docs.microsoft.com/en-us/azure/cognitive-services/speech/how-to/how-to-authentication?tabs=Powershell). It should be noted that the free trial key is valid only for a certain time and has a quota limit.

**Comment by djtech2k** [comment] 2018-01-12 14:11
My subscription is not a trial.

I followed that link and ran the tests.  When running the test of "Use an authorization token in a request", I get an error "Invoke-RestMethod : The remote server returned an error: (403) Forbidden.".  I am able to retrieve the token just fine.

**Comment by zhouwangzw** [comment] 2018-01-12 14:24
I just tried, it works for me with the example using authorization token. Please note that the authorization toke is only valid for 10 minutes.

**Comment by djtech2k** [comment] 2018-01-12 14:26
I followed the article you posted.  I used powershell to execute the tests that get the token, then use the token in a request.  I ran then as a single piece of code, so timeout should not be an issue.  I simply put in my subscription key and the path to a wav file.  I looked at the variables used in the Invoke-RestMethod and all variables have a value.  I do not know why I am getting this 403 Error.

**Comment by djtech2k** [comment] 2018-01-12 14:32
Do I need a key for Bing Speech API or Translator Speech API?  Maybe I am using the wrong key?

**Comment by djtech2k** [comment] 2018-01-12 14:35
I found the issue.  For this github app, I was using the Speech Translator key and not the Bing Speech key.  I put the Bing Speech Key into the app and it worked.

**Comment by zhouwangzw** [comment] 2018-01-12 15:06
Glad to know that the problem is resolved. I am closing the issue. If you have any other problems, please feel free to open a new one.

**Closed by zhouwangzw** 2018-01-12 15:06 UTC
